Repository powsybl/powsybl-optimizer, pull requests merged in 2023-11, with the labels that each got.

#44 Remove addAlgorithmParam method
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/OpenReacParametersDeserializer.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/OpenReacParametersSerializer.java
  open-reac/src/test/java/com/powsybl/openreac/parameters/input/json/OpenReacJsonModuleTest.java
  open-reac/src/test/resources/parameters.json
Labels: Breaking change

#38 DEBUG log level to export debug files
  open-reac/src/main/resources/openreac/reactiveopf.run
  open-reac/src/main/resources/openreac/reactiveopfoutput.run
Labels: AMPL

#40 Two optional parameters to control voltage limits
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/OpenReacParametersDeserializer.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/OpenReacParametersSerializer.java
  open-reac/src/main/resources/openreac/reactiveopf.mod
  open-reac/src/main/resources/openreac/reactiveopf.run
  open-reac/src/main/resources/openreac/reactiveopfexit.run
  open-reac/src/main/resources/openreac/reactiveopfoutput.run
  open-reac/src/test/java/com/powsybl/openreac/OpenReacParametersTest.java
  open-reac/src/test/java/com/powsybl/openreac/OpenReacRunnerTest.java
  open-reac/src/test/java/com/powsybl/openreac/parameters/input/VoltageLevelLimitsOverrideInputTest.java
  open-reac/src/test/java/com/powsybl/openreac/parameters/input/VoltageLimitsOverrideTest.java
  open-reac/src/test/java/com/powsybl/openreac/parameters/input/json/OpenReacJsonModuleTest.java
  open-reac/src/test/resources/expected_inputs/param_algo.txt
  open-reac/src/test/resources/mock_outputs/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-input-algo-parameters/default.txt
  open-reac/src/test/resources/openreac-input-algo-parameters/modified_param_algo.txt
  open-reac/src/test/resources/openreac-output-ieee14/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-real-network/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-shunt/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-svc/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-transfo/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-vsc/reactiveopf_results_indic.txt
  open-reac/src/test/resources/parameters.json
Labels: Java/AMPL

#45 Desactivate transformers checks
  open-reac/src/main/resources/openreac/reactiveopf.run
Labels: AMPL

#41 Add configuration of reactive slacks repartition
  open-reac/src/main/java/com/powsybl/openreac/parameters/OpenReacAmplIOFiles.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/AbstractElementsInput.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/ConfiguredBusesWithReactiveSlack.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/OpenReacParameters.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/algo/ReactiveSlackBusesMode.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/OpenReacParametersDeserializer.java
  open-reac/src/main/java/com/powsybl/openreac/parameters/input/json/OpenReacParametersSerializer.java
  open-reac/src/main/resources/openreac/reactiveopf.dat
  open-reac/src/main/resources/openreac/reactiveopf.mod
  open-reac/src/main/resources/openreac/reactiveopf.run
  open-reac/src/main/resources/openreac/reactiveopfexit.run
  open-reac/src/main/resources/openreac/reactiveopfoutput.run
  open-reac/src/test/java/com/powsybl/openreac/OpenReacParametersTest.java
  open-reac/src/test/java/com/powsybl/openreac/OpenReacRunnerTest.java
  open-reac/src/test/java/com/powsybl/openreac/parameters/input/json/OpenReacJsonModuleTest.java
  open-reac/src/test/resources/expected_inputs/param_algo.txt
  open-reac/src/test/resources/expected_inputs/param_buses_with_reactive_slack.txt
  open-reac/src/test/resources/expected_inputs/param_generators_reactive.txt
  open-reac/src/test/resources/expected_inputs/param_shunts.txt
  open-reac/src/test/resources/expected_inputs/param_transformers.txt
  open-reac/src/test/resources/mock_outputs/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-input-algo-parameters/default.txt
  open-reac/src/test/resources/openreac-input-algo-parameters/modified_param_algo.txt
  open-reac/src/test/resources/openreac-output-ieee14/reactiveopf_results_generators.csv
  open-reac/src/test/resources/openreac-output-ieee14/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-real-network/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-shunt/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-svc/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-transfo/reactiveopf_results_indic.txt
  open-reac/src/test/resources/openreac-output-vsc/reactiveopf_results_indic.txt
  open-reac/src/test/resources/parameters.json
Labels: Java/AMPL
